In [33]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.

import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [34]:
my_array = np.zeros(10)
my_array[4] = 1
my_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [35]:
matrix4 = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
matrix4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [36]:
# solution
arr1 = np.array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
arr2 = np.array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

# addition: arr1 + arr2
arr_addition = arr1 + arr2

# subtraction: arr1 - arr2 
arr_subtraction = arr1 - arr2

# division: arr1 / arr2
arr_division = arr1 / arr2

# multiplication: arr1 * arr2
arr_multiplication = arr1 * arr2

# Result of array operations
arr_addition, arr_subtraction, arr_division, arr_multiplication

(array([[45, 59, 12],
        [11, 48, 26],
        [47, 25, 17]]),
 array([[37,  1,  8],
        [ 1, 22, 20],
        [-1, -7,  3]]),
 array([[10.25      ,  1.03448276,  5.        ],
        [ 1.2       ,  2.69230769,  7.66666667],
        [ 0.95833333,  0.5625    ,  1.42857143]]),
 array([[164, 870,  20],
        [ 30, 455,  69],
        [552, 144,  70]]))

### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [37]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr_slice = arr[2:7]
arr_slice

array([30, 40, 50, 60, 70])

### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [38]:
arr3 = np.array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])

# The mean value
mean_arr3 = np.mean(arr3)
# NB: round the mean to two decimal places
mean_arr3_rounded = round(mean_arr3, 2)

# The sum value
sum_arr3 = np.sum(arr3)

# The maximum value
max_arr3 = np.max(arr3)

# Display the results
mean_arr3_rounded, sum_arr3, max_arr3

(np.float64(24.56), np.int64(221), np.int64(60))

# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [39]:
data = [10, 20, 30, 40, 50]
index_label = ['a', 'b', 'c', 'd', 'e']
pandas_series = pd.Series(data, index=index_label)
pandas_series

a    10
b    20
c    30
d    40
e    50
dtype: int64

### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [40]:
df = pd.read_csv(r'./data/data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: './data/data.csv'

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [ ]:
three_rows = df[:3]
three_rows

### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [ ]:
df['Tax'] = df['Salary'] * 0.10
df

#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [ ]:
filter_age = df[df['Age'] > 36]
filter_age

# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [ ]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

In [ ]:
total_sales_per_region = sales_data.groupby('Region')['Sales'].sum().reset_index()
total_sales_per_region.columns = ['Region', 'TotalSales']

mean_sales_per_region = sales_data.groupby('Region')['Sales'].mean().reset_index()
mean_sales_per_region.columns = ['Region', 'MeanSales']

merged_sales_data = pd.merge(total_sales_per_region, mean_sales_per_region, on='Region')
merged_sales_data

### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [ ]:
from IPython.display import display

customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

display(customers.head(2), orders.head(2))

In [ ]:
merged_data = pd.merge(customers, orders, on='CustomerID')
merged_data

### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [ ]:
from IPython.display import display

# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

display(employees.head(2), departments.head(2))

In [ ]:
left_joined_data = pd.merge(employees, departments, on='DeptID', how='left')
left_joined_data

### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [ ]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

In [ ]:
pivot_table = sales_pivot_data.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='sum')
pivot_table